CREATE TABLE Tbl_DeviceMeasurement (
    IdMeasurement INT NOT NULL AUTO_INCREMENT,
    IdDev VARCHAR(15) NOT NULL,
    TimeMeasure DATETIME NOT NULL,
    Potency FLOAT,
    Voltage FLOAT,
    Charge FLOAT,
    Temperature FLOAT,
    Misc01  FLOAT,
    Misc02  FLOAT,
    Misc03  FLOAT,
    Misc04  FLOAT,
    Misc05  FLOAT,
    Misc06  FLOAT,
    Misc07  FLOAT,
    Misc08  FLOAT,
    Misc09  FLOAT,
    Misc10  FLOAT,
    Misc11  FLOAT,
    Misc12  FLOAT,
    Misc13  FLOAT,
    Misc14  FLOAT,
    Misc15  FLOAT,
    Misc16  FLOAT,
    Misc17  FLOAT,
    Misc18  FLOAT,
    Misc19  FLOAT,
    Misc20  FLOAT,
    CONSTRAINT PK PRIMARY KEY (IdMeasurement),
    FOREIGN KEY (IdDev) REFERENCES Tbl_DeviceGeneralInfo(IdDev)
);