CREATE TABLE Tbl_DeviceConfig (
    IdDev VARCHAR(15) NOT NULL,
    QoS INT,
    CleanSession TINYINT(1),
    Persistance TINYINT(1),
    FrecuencySamplig INT,
    Potency TINYINT(1),
    Voltage TINYINT(1),
    Charge TINYINT(1),
    Temperature TINYINT(1),
    Misc01 TINYINT(1),
    Misc02 TINYINT(1),
    Misc03 TINYINT(1),
    Misc04 TINYINT(1),
    Misc05 TINYINT(1),
    Misc06 TINYINT(1),
    Misc07 TINYINT(1),
    Misc08 TINYINT(1),
    Misc09 TINYINT(1),
    Misc10 TINYINT(1),
    Misc11 TINYINT(1),
    Misc12 TINYINT(1),
    Misc13 TINYINT(1),
    Misc14 TINYINT(1),
    Misc15 TINYINT(1),
    Misc16 TINYINT(1),
    Misc17 TINYINT(1),
    Misc18 TINYINT(1),
    Misc19 TINYINT(1),
    Misc20 TINYINT(1),
    FOREIGN KEY (IdDev) REFERENCES Tbl_DeviceGeneralInfo(IdDev)
);